# Synthetic Data Generation

### This notebook takes the initial and eventual scrape data and merges them together (Initial scraping was done to see what are the relevant features. Another scraping done to comprehensively extract all features that may be required in as we expand tasks in the project)
### Frome the merged data, synthetic data is generated for Biometric Prediction

In [39]:
import pandas as pd
import numpy as np
import random
import ast

from dateutil.relativedelta import relativedelta
from datetime import date

import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

In [40]:
origin_df = pd.read_excel('processed/origin_complete.xlsx')
crime_analysis = pd.read_csv('processed/crime_analysis_results.csv')

In [41]:
print("""
Crime analysis data (from Audrey)
- id, name, aliases
- birth_date, haircolour, height, eyecolour, gender, age_at_first_seen, days_at_large, age_today, age_last_seen
- countries (code of country), Label (country label), address (lowercase ones), sanctions_cleaned, phones, emails
- schema, program_ids, dataset, first_seen, last_seen, last_change

Origin (including network links)
- id, entity_id
- weight, language_spoken_ids, distinguishing_marks
- _embedded.links
- '_links.self.href', '_links.images.href', '_links.thumbnail.href'

""")

df1_cols = [
    'id', 'name', 'aliases',
    'birth_date', 'hairColor', 'height', 'eyeColor', 'GENDER', 'age_at_first_seen', 'days_at_large', 'age_today', 'age_at_last_seen',
    'countries', 'Label', 'address', 'sanctions_clean', 'phones', 'emails',
    'schema', 'program_ids', 'dataset', 'first_seen', 'last_seen', 'last_change'
]

df2_cols = [
    'id', 'entity_id',
    'weight', 'languages_spoken_ids', 'distinguishing_marks',
    '_embedded.links',
    '_links.self.href', '_links.images.href', '_links.thumbnail.href'
]

df1_select = crime_analysis[df1_cols]
df2_select = origin_df[df2_cols]

# display(origin_df)
# display(crime_analysis)

df_final = pd.merge(df1_select, df2_select, how = 'left', on = 'id')
display(df_final)

Crime analysis data (from Audrey)
- id, name, aliases
- birth_date, haircolour, height, eyecolour, gender, age_at_first_seen, days_at_large, age_today, age_last_seen
- countries (code of country), Label (country label), address (lowercase ones), sanctions_cleaned, phones, emails
- schema, program_ids, dataset, first_seen, last_seen, last_change

Origin (including network links)
- id, entity_id
- weight, language_spoken_ids, distinguishing_marks
- _embedded.links
- '_links.self.href', '_links.images.href', '_links.thumbnail.href'

,id,name,aliases,birth_date,hairColor,height,eyeColor,GENDER,age_at_first_seen,days_at_large,age_today,age_at_last_seen,countries,Label,address,sanctions_clean,phones,emails,schema,program_ids,dataset,first_seen,last_seen,last_change,entity_id,weight,languages_spoken_ids,distinguishing_marks,_embedded.links,_links.self.href,_links.images.href,_links.thumbnail.href
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,"['TGK', 'ARA', 'ENG', 'RUS']",NaN,"[{'forename': 'ANDREY', 'color': 'RED', 'name'...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
1,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,tj,Tajikistan,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,"['TGK', 'ARA', 'ENG', 'RUS']",NaN,"[{'forename': 'ANDREY', 'color': 'RED', 'name'...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
2,NK-22baaNEkbgBeZokNLmpaKd,DZHAMBULAT GALIMOV,NaN,1989-01-05,NaN,NaN,NaN,M,35.2,667,36,37.2,ru,Russia,dagestan republic,participation in illegal armed formation,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2016/62557,0.0,"['RUS', 'KUM']",NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
3,NK-282timUs47w9otBkgPN6hw,KHAVA EFENDIEVA,NaN,1982-05-24,BLA,1.75,BLA,F,41.8,667,43,42.8,ru,Russia,"grozny, chechen republic",participation in illegal armed formation,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2021/16004,0.0,['RUS'],NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
4,NK-2Ld7pewCoLeyspMtVCMMMo,JIAN XIA,NaN,1977-07-13,NaN,NaN,NaN,M,46.6,667,48,47.6,cn,China,liaoning,"""1) murder\n2) manslaughter\n3) aggravated theft""",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2010/24537,0.0,"['CHI', 'ENG']",NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7014,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.80,BRO,M,47.0,-12,46,47.1,no,Norway,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,NaN,NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
7015,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.80,BRO,M,47.0,-12,46,47.1,pk,Pakistan,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,NaN,NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
7016,interpol-red-2026-6996,MILOS MEDENICA,NaN,1986-05-20,NaN,NaN,NaN,M,39.7,-31,39,38.8,me,Montenegro,kolasin,"""– establishment of a criminal organization, \...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/6996,NaN,['SRP'],NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
7017,interpol-red-2026-7397,ALEXANDER JAVIER QUIJADA MOJICA,NaN,2000-04-24,BLA,NaN,NaN,M,25.8,-31,25,24.9,pa,Panama,panama,homicidio,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/7397,0.0,NaN,TEZ CLARA,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN
7018,interpol-red-2026-8243,LEANDRO SANTANA DE PAULA,NaN,1982-05-31,NaN,NaN,NaN,NaN,43.7,-38,43,42.8,br,Brazil,unknown,tráfico internacional de drogas y asociación p...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-02-07 01:08:22,2026-03-07 09:27:01,2026-02-07 01:08:22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
def process_list_string(s):
    if pd.isna(s): # Handles actual NaN values in the column
        return None
    try:
        # Try evaluating after replacing 'nan' with 'None'
        return ast.literal_eval(s.replace('nan', 'None'))
    except (ValueError, SyntaxError):
        # Handle cases where the string is not a list format, e.g., a single value
        return s

def normalise_data(df, col):
    normalised = pd.json_normalize(df)
    normalised = normalised.add_prefix('(' + col +')')
    return normalised

def calculate_detailed_age(born):
    # Check if 'born' is NaT or None
    if pd.isnull(born):
        return None
    
    today = date.today()
    # Ensure 'born' is a date object, as pandas timestamps can sometimes 
    # behave differently with relativedelta
    age = relativedelta(today, born.date())
    return age

In [43]:
df_final['languages_spoken_ids'] = df_final['languages_spoken_ids'].apply(process_list_string)
df_final['_embedded.links'] = df_final['_embedded.links'].apply(process_list_string)

In [44]:
cols_to_explode = ['languages_spoken_ids', '_embedded.links']

for col in cols_to_explode:
    df_final = df_final.explode(col)

In [45]:
df_final = df_final.reset_index(drop=True)
df_final

,id,name,aliases,birth_date,hairColor,height,eyeColor,GENDER,age_at_first_seen,days_at_large,age_today,age_at_last_seen,countries,Label,address,sanctions_clean,phones,emails,schema,program_ids,dataset,first_seen,last_seen,last_change,entity_id,weight,languages_spoken_ids,distinguishing_marks,_embedded.links,_links.self.href,_links.images.href,_links.thumbnail.href
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
1,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ARA,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
2,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ENG,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
3,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,RUS,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
4,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,tj,Tajikistan,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10043,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,no,Norway,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
10044,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,pk,Pakistan,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
10045,interpol-red-2026-6996,MILOS MEDENICA,NaN,1986-05-20,NaN,NaN,NaN,M,39.7,-31,39,38.8,me,Montenegro,kolasin,"""– establishment of a criminal organization, \...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/6996,NaN,SRP,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
10046,interpol-red-2026-7397,ALEXANDER JAVIER QUIJADA MOJICA,NaN,2000-04-24,BLA,NaN,NaN,M,25.8,-31,25,24.9,pa,Panama,panama,homicidio,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/7397,0.0,None,TEZ CLARA,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN
10047,interpol-red-2026-8243,LEANDRO SANTANA DE PAULA,NaN,1982-05-31,NaN,NaN,NaN,NaN,43.7,-38,43,42.8,br,Brazil,unknown,tráfico internacional de drogas y asociación p...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-02-07 01:08:22,2026-03-07 09:27:01,2026-02-07 01:08:22,NaN,NaN,None,NaN,None,NaN,NaN,NaN

In [46]:
df_normalise = pd.concat([df_final, normalise_data(df_final['_embedded.links'], 'embedded_links')], axis= 1)
df_normalise

,id,name,aliases,birth_date,hairColor,height,eyeColor,GENDER,age_at_first_seen,days_at_large,age_today,age_at_last_seen,countries,Label,address,sanctions_clean,phones,emails,schema,program_ids,dataset,first_seen,last_seen,last_change,entity_id,weight,languages_spoken_ids,distinguishing_marks,_embedded.links,_links.self.href,_links.images.href,_links.thumbnail.href,(embedded_links)forename,(embedded_links)color,(embedded_links)name,(embedded_links)entity_id,(embedded_links)_links.self.href,(embedded_links)_links.thumbnail.href
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,ANDREY,RED,NIKITENKO,2019/102608,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
1,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ARA,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,ANDREY,RED,NIKITENKO,2019/102608,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
2,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ENG,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,ANDREY,RED,NIKITENKO,2019/102608,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
3,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,RUS,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,ANDREY,RED,NIKITENKO,2019/102608,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
4,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,tj,Tajikistan,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,ANDREY,RED,NIKITENKO,2019/102608,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10043,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,no,Norway,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN,NaN,NaN,NaN,NaN
10044,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,pk,Pakistan,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN,NaN,NaN,NaN,NaN
10045,interpol-red-2026-6996,MILOS MEDENICA,NaN,1986-05-20,NaN,NaN,NaN,M,39.7,-31,39,38.8,me,Montenegro,kolasin,"""– establishment of a criminal organization, \...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/6996,NaN,SRP,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN,NaN,NaN,NaN,NaN
10046,interpol-red-2026-7397,ALEXANDER JAVIER QUIJADA MOJICA,NaN,2000-04-24,BLA,NaN,NaN,M,25.8,-31,25,24.9,pa,Panama,panama,homicidio,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/7397,0.0,None,TEZ CLARA,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10047,interpol-red-2026-8243,LEANDRO SANTANA DE PAULA,NaN,1982-05-31,NaN,NaN,NaN,NaN,43.7,-38,43,42.8,br,Brazil,unknown,tráfico internacional de drogas y asociación p...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-02-07 01:08:22,2026-03-07 09:27:01,2026-02-07 01:08:22,NaN,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df_normalise = df_normalise.drop(columns = [ '_embedded.links'])

In [48]:
df_normalise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10048 entries, 0 to 10047
Data columns (total 37 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     10048 non-null  object
 1   name                                   10048 non-null  object
 2   aliases                                6 non-null      object
 3   birth_date                             9771 non-null   object
 4   hairColor                              5065 non-null   object
 5   height                                 4889 non-null   float64
 6   eyeColor                               4537 non-null   object
 7   GENDER                                 10028 non-null  object
 8   age_at_first_seen                      9771 non-null   float64
 9   days_at_large                          10048 non-null  int64
 10  age_today                              10048 non-null  int64
 11  age_at_last_seen                       9771 non-null   float64
 12  countries                              9998 non-null   object
 13  Label                                  9998 non-null   object
 14  address                                10048 non-null  object
 15  sanctions_clean                        10047 non-null  object
 16  phones                                 0 non-null      float64
 17  emails                                 0 non-null      float64
 18  schema                                 10048 non-null  object
 19  program_ids                            10047 non-null  object
 20  dataset                                10048 non-null  object
 21  first_seen                             10048 non-null  object
 22  last_seen                              10048 non-null  object
 23  last_change                            10048 non-null  object
 24  entity_id                              10033 non-null  object
 25  weight                                 8139 non-null   float64
 26  languages_spoken_ids                   9233 non-null   object
 27  distinguishing_marks                   1140 non-null   object
 28  _links.self.href                       10033 non-null  object
 29  _links.images.href                     10033 non-null  object
 30  _links.thumbnail.href                  9665 non-null   object
 31  (embedded_links)forename               257 non-null    object
 32  (embedded_links)color                  257 non-null    object
 33  (embedded_links)name                   257 non-null    object
 34  (embedded_links)entity_id              257 non-null    object
 35  (embedded_links)_links.self.href       257 non-null    object
 36  (embedded_links)_links.thumbnail.href  251 non-null    object
dtypes: float64(6), int64(2), object(29)
memory usage: 2.8+ MB

In [49]:
df_normalise['network_name'] = df_normalise['(embedded_links)forename'] + ' ' + df_normalise['(embedded_links)name']
df_normalise = df_normalise.rename(columns = {'(embedded_links)entity_id': 'network_entity_id'})
df_normalise = df_normalise.drop(columns = [
    '(embedded_links)color',
    '(embedded_links)forename',
    '(embedded_links)name',
    '(embedded_links)_links.self.href',
    '(embedded_links)_links.thumbnail.href'
])
df_normalise

,id,name,aliases,birth_date,hairColor,height,eyeColor,GENDER,age_at_first_seen,days_at_large,age_today,age_at_last_seen,countries,Label,address,sanctions_clean,phones,emails,schema,program_ids,dataset,first_seen,last_seen,last_change,entity_id,weight,languages_spoken_ids,distinguishing_marks,_links.self.href,_links.images.href,_links.thumbnail.href,network_entity_id,network_name
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,2019/102608,ANDREY NIKITENKO
1,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ARA,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,2019/102608,ANDREY NIKITENKO
2,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ENG,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,2019/102608,ANDREY NIKITENKO
3,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,RUS,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,2019/102608,ANDREY NIKITENKO
4,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,tj,Tajikistan,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,2019/102608,ANDREY NIKITENKO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10043,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,no,Norway,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN
10044,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,pk,Pakistan,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN
10045,interpol-red-2026-6996,MILOS MEDENICA,NaN,1986-05-20,NaN,NaN,NaN,M,39.7,-31,39,38.8,me,Montenegro,kolasin,"""– establishment of a criminal organization, \...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/6996,NaN,SRP,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN
10046,interpol-red-2026-7397,ALEXANDER JAVIER QUIJADA MOJICA,NaN,2000-04-24,BLA,NaN,NaN,M,25.8,-31,25,24.9,pa,Panama,panama,homicidio,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/7397,0.0,None,TEZ CLARA,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN,NaN
10047,interpol-red-2026-8243,LEANDRO SANTANA DE PAULA,NaN,1982-05-31,NaN,NaN,NaN,NaN,43.7,-38,43,42.8,br,Brazil,unknown,tráfico internacional de drogas y asociación p...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-02-07 01:08:22,2026-03-07 09:27:01,2026-02-07 01:08:22,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df_normalise['aliases'].value_counts()

aliases
KHUSEYN AKTAMIROV    4
GUSEIN GASANOV       2
Name: count, dtype: int64

In [51]:
# save the mega data for synthetic data generation
df_normalise.to_csv('processed/mega_sanctions_final.csv', index=False)

## Generating Synthetic Client Data (To Train & Test Models)
Total Records: 10,000
- Matches (Sanctioned): 500 (5% of the data)
- Non-matches (Clean): 9,500 (95% of the data) - reflecting real-world scenarios where most clients are not sanctioned.
- Target Column: match_label (1 = Sanctioned, 0 = Clean).

The synthetic data includes only typical client-facing features, excluding internal sanction descriptions and crime details:
- client_id: A unique identifier (e.g., C000001).
- full_name: Realistic names derived and shuffled from the original dataset.
- date_of_birth: Formatted as YYYY-MM-DD.
- gender: M/F/Other.
- nationality_code: Two-letter country codes (e.g., ru, tj, co).
- height_cm & weight_kg: Numerical biometric data.
- hair_color & eye_color: Categorical biometric descriptors.
- spoken_languages: Three-letter language codes.

Key Considerations:
- Synthetic data maintains biometric sparsity (e.g. 50% of original data lacked hair colour and eye colour, which is reflected
- For the 500 matches, minor variations were introduced (e.g. name misspelling, height difference, date of birth alteration) to reflect real world data

In [137]:
# HELPER FUNCTIONS

# ── Placeholder colour pools (used by introduce_fuzzy before matches are built)
matches_hair = df_normalise['hairColor'].dropna().unique().tolist()
matches_eye  = df_normalise['eyeColor'].dropna().unique().tolist()

names_pool = df_normalise['name'].dropna().unique()
FIRST_NAMES_POOL = [n.split()[0] for n in names_pool if len(n.split()) > 0]
LAST_NAMES_POOL = [n.split()[-1] for n in names_pool if len(n.split()) > 1]

def generate_random_name():
    # Sampling from a pre-made list is near-instant
    fn = np.random.choice(FIRST_NAMES_POOL)
    ln = np.random.choice(LAST_NAMES_POOL)
    return f"{fn} {ln}"

def introduce_fuzzy(row):
    """
    Role the dice to choose whether we create variability for name, height, or birth date
    The names will be altered through random swapping of characters for names length > 5
    The date of birth will be altered at either year, month, day or mixed:
        - year: 1 to 3
        - month: 1 to 6
        - day: 1 to 20
    The height will be altered by +-3cm if height is not null
    """
    # Misspell name slightly
    name = str(row['full_name'])
    if len(name) > 5:
        strategy = random.choice(['swap', 'shuffle_slice', 'drop', 'duplicate'])
        char_list = list(name)
        
        if strategy == 'swap':
            idx = random.randint(0, len(char_list) - 2)
            char_list[idx], char_list[idx+1] = char_list[idx+1], char_list[idx]
            
        elif strategy == 'shuffle_slice':
            slice_len = min(random.randint(3, 4), len(char_list))
            start_idx = random.randint(0, len(char_list) - slice_len)
            slice_chars = char_list[start_idx:start_idx + slice_len]
            random.shuffle(slice_chars)
            char_list[start_idx:start_idx + slice_len] = slice_chars
            
        elif strategy == 'drop':
            char_list.pop(random.randint(0, len(char_list) - 1))
            
        elif strategy == 'duplicate':
            idx = random.randint(0, len(char_list) - 1)
            char_list.insert(idx, char_list[idx])
        
        row['full_name'] = "".join(char_list)
        
     # Modify height by +/- 1 to 5
    if pd.notnull(row['height_m']) and row['height_m'] > 0:
        row['height_m'] += random.uniform(-0.03, 0.03)
    
    # Modify age anywhere between 1 to 3 years, 1 to 6 months, 1 to 20 days
    if pd.notnull(row['date_of_birth']):
        try:
            dt = pd.to_datetime(row['date_of_birth'])
            
            # Pick a random shift type
            shift_type = random.choice(['year', 'month', 'day', 'mix'])
            
            if shift_type == 'year':
                # Shift 1 to 3 years
                dt += relativedelta(years=random.randint(1, 3) * random.choice([-1, 1])) # change from 10 years to 3 years (+/-)
            elif shift_type == 'month':
                # Shift 1 to 6 months
                dt += relativedelta(months=random.randint(1, 6) * random.choice([-1, 1]))
            elif shift_type == 'day':
                # Shift 1 to 20 days
                dt += relativedelta(days=random.randint(1, 20) * random.choice([-1, 1]))
            else:
                # A mix of small changes to simulate general data entry error
                dt += relativedelta(
                    years=random.randint(0, 2) * random.choice([-1, 1]),
                    months=random.randint(0, 3) * random.choice([-1, 1]),
                    days=random.randint(1, 10) * random.choice([-1, 1])
                )
            
            row['date_of_birth'] = dt.strftime('%Y-%m-%d')
        except Exception:
            pass # Fallback in case of conversion errors

        # Modify hair and eye colour
        change_hair = random.choice([0,1])
        change_eye = random.choice([0,1])

        if change_hair == 1:
            # pick random hair colour
            colour = random.choice(matches_hair)
            row['hairColor'] = colour

        if change_eye == 1:
            # pick random hair colour
            colour = random.choice(matches_eye)
            row['eyeColor'] = colour
            
    return row

# Distribution sampling function
def sample_from_dist(col_name, size):
    """
    Helper function to randomly sample data from original sanctions dataset for the non-matched clients.
    The rest of the unsampled data will have random generated names
    """
    dist = distributions[col_name]
    # .values is faster than .tolist() for numpy operations
    return np.random.choice(dist.index.values, size=size, p=dist.values)

In [143]:
# Load the dataset
df = pd.read_csv('processed/mega_sanctions_final.csv')

# Inspect the columns and the first few rows
print(df.columns.tolist())

# Identify columns suitable for client data
# name, birth_date, hairColor, height, eyeColor, GENDER, countries (maybe map to nationality), weight, languages_spoken_ids
client_cols = ['id', 'name', 'birth_date', 'hairColor', 'height', 'eyeColor', 'GENDER', 'countries', 'weight']

# filter to relevant columns
df = df[client_cols].drop_duplicates().reset_index(drop = True)
display(df)
display(df.info())

# Check missingness
missing_stats = df.isnull().mean()
print("\nMissingness in client columns:")
print(missing_stats)

['id', 'name', 'aliases', 'birth_date', 'hairColor', 'height', 'eyeColor', 'GENDER', 'age_at_first_seen', 'days_at_large', 'age_today', 'age_at_last_seen', 'countries', 'Label', 'address', 'sanctions_clean', 'phones', 'emails', 'schema', 'program_ids', 'dataset', 'first_seen', 'last_seen', 'last_change', 'entity_id', 'weight', 'languages_spoken_ids', 'distinguishing_marks', '_links.self.href', '_links.images.href', '_links.thumbnail.href', 'network_entity_id', 'network_name']

,id,name,birth_date,hairColor,height,eyeColor,GENDER,countries,weight
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,1992-06-28,OTHD,NaN,OTHD,F,ru,0.0
1,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,1992-06-28,OTHD,NaN,OTHD,F,tj,0.0
2,NK-22baaNEkbgBeZokNLmpaKd,DZHAMBULAT GALIMOV,1989-01-05,NaN,NaN,NaN,M,ru,0.0
3,NK-282timUs47w9otBkgPN6hw,KHAVA EFENDIEVA,1982-05-24,BLA,1.75,BLA,F,ru,0.0
4,NK-2Ld7pewCoLeyspMtVCMMMo,JIAN XIA,1977-07-13,NaN,NaN,NaN,M,cn,0.0
...,...,...,...,...,...,...,...,...,...
7012,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,1979-01-19,BLA,1.80,BRO,M,no,NaN
7013,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,1979-01-19,BLA,1.80,BRO,M,pk,NaN
7014,interpol-red-2026-6996,MILOS MEDENICA,1986-05-20,NaN,NaN,NaN,M,me,NaN
7015,interpol-red-2026-7397,ALEXANDER JAVIER QUIJADA MOJICA,2000-04-24,BLA,NaN,NaN,M,pa,0.0
7016,interpol-red-2026-8243,LEANDRO SANTANA DE PAULA,1982-05-31,NaN,NaN,NaN,NaN,br,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7017 entries, 0 to 7016
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          7017 non-null   object
 1   name        7017 non-null   object
 2   birth_date  6890 non-null   object
 3   hairColor   3281 non-null   object
 4   height      3183 non-null   float64
 5   eyeColor    2921 non-null   object
 6   GENDER      6998 non-null   object
 7   countries   6972 non-null   object
 8   weight      5509 non-null   float64
dtypes: float64(2), object(7)
memory usage: 493.5+ KB

None

Missingness in client columns:
id            0.000000
name          0.000000
birth_date    0.018099
hairColor     0.532421
height        0.546387
eyeColor      0.583725
GENDER        0.002708
countries     0.006413
weight        0.214907
dtype: float64

In [144]:
# Select client columns
client_cols = ['name', 'birth_date', 'hairColor', 'height', 'eyeColor', 'GENDER', 'countries', 'weight']

# Extract distributions for non-matches
distributions = {}
for col in client_cols:
    if col != 'name':
        # Get counts including NaNs
        distributions[col] = df[col].value_counts(dropna=False, normalize=True)

# Check distributions
print(distributions['GENDER'])
print(distributions['hairColor'])
print(distributions['weight'])

GENDER
M      0.859627
F      0.137666
NaN    0.002708
Name: proportion, dtype: float64
hairColor
NaN      0.532421
BLA      0.262363
OTHD     0.133533
BRO      0.031637
BROF     0.012256
GRY      0.009406
GRYG     0.004988
HAIB     0.003705
YELB     0.003278
RED      0.001995
WHI      0.001425
REDA     0.001283
HAID     0.001140
YELBD    0.000428
BROL     0.000143
Name: proportion, dtype: float64
weight
0.0      0.573607
NaN      0.214907
60.0     0.018241
70.0     0.016531
65.0     0.014964
           ...
90.5     0.000143
94.0     0.000143
136.0    0.000143
108.0    0.000143
230.0    0.000143
Name: proportion, Length: 118, dtype: float64

In [145]:
df['id'].value_counts()

id
interpol-red-2015-43692    3
interpol-red-2015-74874    3
interpol-red-2022-82960    3
interpol-red-2007-30259    3
interpol-red-2014-67594    3
                          ..
interpol-red-2016-62292    1
interpol-red-2016-62282    1
interpol-red-2016-62143    1
interpol-red-2016-62102    1
interpol-red-2026-8243     1
Name: count, Length: 6436, dtype: int64

In [167]:
df['id'].nunique()

6436

In [162]:
random.seed(10)

# Number of rows
n_total = 100000 # generate altogether 100,000 synthetic clients
# n_matches_6k = df['id'].nunique()
# get the exact 6k number of rows for exact matches
# generate additional 3k rows with variation so that altogether we have 10,000 matches (10%)
n_matches_w_variations = 10000 -  df['id'].nunique()
n_non_matches = n_total - 10000 # 90% non-matches 

# 1. Generate additional 3k matches with variation
matches_orig = df.sample(n=n_matches_w_variations, random_state=42)

# Select client-relevant columns
client_map = {
    'name': 'full_name',
    'birth_date': 'date_of_birth',
    'GENDER': 'gender',
    'countries': 'nationality_code',
    'height': 'height_m',
    'weight': 'weight_kg',
    'hairColor': 'hair_color',
    'eyeColor': 'eye_color'
}

matches_3k = matches_orig[list(client_map.keys()) + ['id']].rename(columns=client_map)
matches_3k = matches_3k.rename(columns={'id': 'matched_sanction_id'})
matches_3k = matches_3k.apply(introduce_fuzzy, axis=1)

# 2. Add 6k interpol bad actors without variation
matches_6k = df.drop_duplicates(subset=['id'], keep='first').reset_index(drop=True)
matches_6k = matches_6k[list(client_map.keys()) + ['id']].rename(columns=client_map)
matches_6k = matches_6k.rename(columns={'id': 'matched_sanction_id'})

matches = pd.concat([matches_3k, matches_6k])
matches['match_label'] = 1

matches_hair = matches['hair_color'].unique().tolist()
matches_eye = matches['eye_color'].unique().tolist()

print("Matches - 10,000")
display(matches)

# 3. Generate 50% of good actors with variation
# 50% of non-matches
n_non_matches_w_variation = int(n_non_matches * 0.5)

# Define non-match data
non_matches_data = {}

# removed because we also want to choose the id which can be generated into both bad and good actors
# matches_id = set(matches_orig)
# df_non_matches = df[~df['id'].isin(matches_id)]

# Sample random IDs from original sanctions list for non-matches
non_matches_data['matched_sanction_id'] = df['id'].sample(n=n_non_matches_w_variation, replace=True, random_state=7).values

for orig_col, new_col in client_map.items():
    if orig_col == 'name':
        # Generate random names
        non_matches_data[new_col] = [generate_random_name() for _ in range(n_non_matches_w_variation)]
    else:
        non_matches_data[new_col] = sample_from_dist(orig_col, n_non_matches_w_variation)

non_matches_var = pd.DataFrame(non_matches_data)

# Ensure non-matches aren't actually in the sanctions list by checking names
sanctioned_names = set(df['name'].str.upper().tolist())
# If a generated name is in sanctioned_names, regenerate it
non_matches_var['full_name'] = non_matches_var['full_name'].apply(
    lambda x: generate_random_name() if str(x).upper() in sanctioned_names else x
)

# 4. Generate 50% of non-match to have same name
n_non_match_novar = n_non_matches - n_non_matches_w_variation

non_match_novar = df[['id', 'name']].sample(n=n_non_match_novar, replace=True, random_state=7)
non_match_novar = non_match_novar.rename(columns = {'id': 'matched_sanction_id', 'name': 'full_name'})

for orig_col, new_col in client_map.items():
    if orig_col == 'name':
        continue
    else:
        non_match_novar[new_col] = sample_from_dist(orig_col, n_non_match_novar)

non_match = pd.concat([non_matches_var, non_match_novar]).reset_index(drop = True)
non_match['match_label'] = 0

print('Non-matches - 90,000')
display(non_match)

# 3. COMBINE AND SHUFFLE
synthetic_df = pd.concat([matches, non_match], ignore_index=True)
synthetic_df = synthetic_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Add a synthetic client_id
synthetic_df['client_id'] = ['C' + str(i).zfill(6) for i in range(1, n_total + 1)]

# Reorder columns
final_cols = ['client_id', 'full_name', 'date_of_birth', 'gender', 'nationality_code',
              'height_m', 'weight_kg', 'hair_color', 'eye_color', 'match_label', 'matched_sanction_id']
synthetic_df = synthetic_df[final_cols]

print('Full synthetic data - 100,000')
display(synthetic_df)

# Save to CSV
synthetic_df.to_csv('synthetic_client_data.csv', index=False)

# # Quick check on distributions
# print("\nSynthetic data missingness:")
# print(synthetic_df.isnull().mean())
# print("\nMatch count:")
# print(synthetic_df['match_label'].value_counts())
# print("\nFirst 10 rows:")
# print(synthetic_df.head(10))

Matches - 10,000

,date_of_birth,eyeColor,eye_color,full_name,gender,hairColor,hair_color,height_m,matched_sanction_id,nationality_code,weight_kg,match_label
2997,1984-09-29,NaN,NaN,PERIKHANUM EMRIALIEVA,F,NaN,OTHD,NaN,interpol-red-2017-13363,ru,0.0,1
3977,1992-10-02,BROL,BLA,GURJINNDER SINGH,M,NaN,BLA,1.724565,interpol-red-2018-22281,in,69.0,1
245,1976-07-31,OTHD,NaN,ARKADIUSZ ANDRZEJ BRILL,M,NaN,NaN,NaN,NK-WQ2EUu8zSyBdyFqWjbg7Xb,pl,NaN,1
1467,1976-08-07,BROH,NaN,FILIPP KOOSMSA,M,REDA,NaN,NaN,interpol-red-2013-62891,ru,0.0,1
1835,1995-07-26,NaN,NaN,DIBIRMAGOMED NASIOV,M,NaN,OTHD,1.597037,interpol-red-2015-35355,ru,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
6431,1978-10-22,NaN,NaN,MICHAL ZBIGNIEW BARYS,M,NaN,NaN,NaN,interpol-red-2026-6812,pl,NaN,1
6432,1979-01-19,NaN,BRO,MOHAMMAD SHAHZAD GULL,M,NaN,BLA,1.800000,interpol-red-2026-688,no,NaN,1
6433,1986-05-20,NaN,NaN,MILOS MEDENICA,M,NaN,NaN,NaN,interpol-red-2026-6996,me,NaN,1
6434,2000-04-24,NaN,NaN,ALEXANDER JAVIER QUIJADA MOJICA,M,NaN,BLA,NaN,interpol-red-2026-7397,pa,0.0,1
6435,1982-05-31,NaN,NaN,LEANDRO SANTANA DE PAULA,NaN,NaN,NaN,NaN,interpol-red-2026-8243,br,NaN,1

Non-matches - 90,000

,matched_sanction_id,full_name,date_of_birth,gender,nationality_code,height_m,weight_kg,hair_color,eye_color,match_label
0,interpol-red-2018-63545,GAZIMAGOMED CRISTIANU,1991-04-22,M,us,1.72,NaN,BLA,BLA,0
1,interpol-red-2012-296014,WALTER TSECHOEV,1953-06-01,F,ru,NaN,NaN,BLA,BLA,0
2,interpol-red-1998-20764,MARIAN SOSA,1996-10-05,M,gt,1.77,NaN,nan,nan,0
3,interpol-red-2016-55195,KAMIL RIVERO,1969-12-22,M,sv,1.72,0.0,BLA,nan,0
4,interpol-red-2021-15339,SHAMKHAN SARACHO,1989-12-28,M,sv,NaN,0.0,BLA,BROD,0
...,...,...,...,...,...,...,...,...,...,...
89995,interpol-red-2018-6795,JOSE NEFTALI ARGUETA SANCHEZ,1990-12-13,M,ru,NaN,68.0,nan,nan,0
89996,interpol-red-2009-11521,ZARGAN BALAEVA,1974-09-04,M,np,1.77,68.0,BLA,nan,0
89997,interpol-red-2009-15726,ASIF MUSAEV,1968-05-14,M,rw,1.77,91.0,nan,nan,0
89998,interpol-red-2022-5001,ALEKSANDR ALIEV,nan,F,ru,NaN,NaN,BLA,BROH,0
89999,interpol-red-2014-6136,ANDREY CHERNYSHEV,1966-01-15,F,pe,NaN,0.0,BLA,nan,0

Full synthetic data - 100,000

,client_id,full_name,date_of_birth,gender,nationality_code,height_m,weight_kg,hair_color,eye_color,match_label,matched_sanction_id
0,C000001,AARON MACARONE MOTSA,1959-09-29,F,py,1.65,0.0,nan,nan,0,interpol-red-2015-42000
1,C000002,ASIA DAKHKILGOVA,1988-12-10,M,ru,NaN,0.0,nan,nan,0,interpol-red-2019-44001
2,C000003,ALEKSANDR PULGAR,1991-02-23,M,np,NaN,0.0,nan,BRO,0,interpol-red-2016-64765
3,C000004,TIMUR ABDURAKHMANOV,nan,M,co,1.75,0.0,BLA,nan,0,interpol-red-2021-19548
4,C000005,SIMEON MIHAYLOV HRISTOV,1994-11-04,M,tr,1.72,NaN,nan,BRO,0,interpol-red-2017-162255
...,...,...,...,...,...,...,...,...,...,...,...
99995,C099996,THI HIEN DINH,1961-02-21,F,vn,NaN,NaN,BLA,BRO,1,interpol-red-2017-144705
99996,C099997,RASUL HERNANDEZ,1988-10-08,F,vn,NaN,82.0,nan,nan,0,interpol-red-2016-38988
99997,C099998,MAGOMED-ALI ISRAILOV,1985-07-12,M,mx,NaN,NaN,nan,nan,0,NK-mB3Pictdsd6M363Nxp4yeS
99998,C099999,RAFAEL MARTÍNEZ AGURETA,1961-08-08,M,sv,NaN,0.0,NaN,NaN,1,interpol-red-2021-79552
99999,C100000,RONALD NAURBAEV,1993-10-29,F,sv,NaN,0.0,nan,nan,0,interpol-red-2016-63317

In [164]:
synthetic_df['matched_sanction_id'].value_counts()

matched_sanction_id
interpol-red-2015-74874      54
interpol-red-2012-331112     51
interpol-red-2017-135470     51
interpol-red-2017-204060     51
interpol-red-2012-325494     50
                             ..
interpol-red-2017-197825      1
interpol-red-2018-87201       1
interpol-red-2014-36050       1
NK-MvE2jEC9JT8jV9FDXofztL     1
interpol-red-2015-41950       1
Name: count, Length: 6436, dtype: int64

In [165]:
synthetic_df[synthetic_df['matched_sanction_id']=='interpol-red-2012-325494']

,client_id,full_name,date_of_birth,gender,nationality_code,height_m,weight_kg,hair_color,eye_color,match_label,matched_sanction_id
2530,C002531,DANIYAL SALGADO,1980-10-22,M,ru,NaN,80.0,OTHD,nan,0,interpol-red-2012-325494
4079,C004080,TAI CHEN,nan,M,hn,1.78,NaN,nan,nan,0,interpol-red-2012-325494
5074,C005075,BOSKO CRUZ,1995-07-23,M,ca,1.65,0.0,nan,BLA,0,interpol-red-2012-325494
9668,C009669,TAI CHEN,1968-05-20,M,kz,NaN,NaN,nan,nan,0,interpol-red-2012-325494
14040,C014041,ISLAM DZHANGURAZOVA,1996-06-17,F,ru,1.73,50.0,nan,nan,0,interpol-red-2012-325494
17180,C017181,FARMAN FENG,1986-11-13,M,in,NaN,0.0,BLA,nan,0,interpol-red-2012-325494
19224,C019225,TAI CHEN,1977-11-29,F,ua,NaN,75.0,nan,nan,0,interpol-red-2012-325494
19312,C019313,BAPARY RIVAS,1994-10-12,M,kz,NaN,90.0,nan,OTHD,0,interpol-red-2012-325494
20942,C020943,TAI CHEN,1954-10-03,M,cn,NaN,NaN,BLA,BRO,1,interpol-red-2012-325494
22692,C022693,AMINAT GRIDNEV,1973-07-07,M,sv,1.87,0.0,nan,BROD,0,interpol-red-2012-325494
23984,C023985,TAI CHHEN,1952-08-10,M,us,NaN,NaN,BLA,BRO,1,interpol-red-2012-325494
25572,C025573,KHAVAZHI SALAZAR,1973-12-23,M,ba,1.70,0.0,nan,nan,0,interpol-red-2012-325494
25877,C025878,TAI CHEN,1994-09-01,M,in,NaN,60.0,nan,nan,0,interpol-red-2012-325494
26754,C026755,TAI CHEN,1971-06-05,M,ru,1.69,81.0,GRY,BRO,0,interpol-red-2012-325494
26878,C026879,TAI CHEN,1958-01-25,M,sv,NaN,0.0,OTHD,nan,0,interpol-red-2012-325494
28873,C028874,WALTER KHASAEV,1946-07-01,M,bo,NaN,0.0,nan,nan,0,interpol-red-2012-325494
30818,C030819,TAI CHEN,1996-11-05,M,mx,NaN,0.0,nan,BLA,0,interpol-red-2012-325494
33019,C033020,SALVADOR RIVAS,1970-04-12,M,ar,1.73,0.0,nan,nan,0,interpol-red-2012-325494
33518,C033519,TAI CHEN,1987-07-05,M,ru,NaN,0.0,nan,BRO,0,interpol-red-2012-325494
35871,C035872,TAI CHEN,1973-03-23,M,ba,NaN,NaN,nan,nan,0,interpol-red-2012-325494
39025,C039026,ABASYN HERNANDEZ,1987-09-05,M,ru,1.70,NaN,BLA,BLA,0,interpol-red-2012-325494
41484,C041485,DANIEL MADRID,1993-09-07,M,gy,1.74,60.0,nan,nan,0,interpol-red-2012-325494
43848,C043849,TAI CHEN,1982-03-19,M,uz,1.68,0.0,OTHD,BLA,0,interpol-red-2012-325494
45535,C045536,ALIBEK GUSEINOV,1987-03-01,M,ru,NaN,56.0,nan,nan,0,interpol-red-2012-325494
46589,C046590,JORGE DASCHBACH,1990-09-02,M,ru,NaN,NaN,OTHD,nan,0,interpol-red-2012-325494
46678,C046679,TAI CHEN,1956-09-17,M,ru,NaN,0.0,OTHD,OTHL,0,interpol-red-2012-325494
47552,C047553,DUSAN MAKAEV,1989-07-25,F,az,1.80,0.0,nan,BROD,0,interpol-red-2012-325494
47611,C047612,TAI CHEN,1980-10-05,M,ru,1.73,NaN,nan,BRO,0,interpol-red-2012-325494
51473,C051474,TAI CHEN,1984-08-24,M,hr,NaN,0.0,OTHD,BLA,0,interpol-red-2012-325494
52520,C052521,TAI CHEN,1990-02-06,M,sy,NaN,0.0,OTHD,BRO,0,interpol-red-2012-325494
53307,C053308,TAI CHEN,1992-06-19,M,ru,1.75,0.0,nan,OTHD,0,interpol-red-2012-325494
53431,C053432,FAYZIDDIN SALGADO,1945-05-01,M,ge,NaN,0.0,OTHD,BRO,0,interpol-red-2012-325494
53934,C053935,TAI CHEN,1992-04-18,F,ru,1.67,NaN,OTHD,nan,0,interpol-red-2012-325494
54170,C054171,TAI CHEN,1971-05-16,F,ru,NaN,NaN,BLA,BLU,0,interpol-red-2012-325494
55368,C055369,MUHAMMAD VARAEV,1984-01-28,M,ru,NaN,0.0,nan,nan,0,interpol-red-2012-325494
61195,C061196,TAI CHEN,1977-04-17,M,sv,1.80,0.0,OTHD,nan,0,interpol-red-2012-325494
62121,C062122,TAI CHEN,1966-05-22,M,ru,1.70,0.0,nan,nan,0,interpol-red-2012-325494
64794,C064795,JOSE MUSAVUZOV,1988-06-15,F,in,NaN,0.0,OTHD,BRO,0,interpol-red-2012-325494
66443,C066444,FERMAN MANCIA,1991-02-28,M,ru,NaN,0.0,OTHD,GRY,0,interpol-red-2012-325494
69731,C069732,HUSEIN MAGOMEDOV,1982-07-02,M,ru,1.70,0.0,BLA,BRO,0,interpol-red-2012-325494
76748,C076749,NASIIAT KHANMAGOMEDOVA,1964-04-12,M,ar,NaN,0.0,nan,nan,0,interpol-red-2012-325494
79463,C079464,TAI CHEN,1988-08-18,M,us,NaN,0.0,BLA,OTHD,0,interpol-red-2012-325494
88795,C088796,OSCAR ANDRES,1985-05-14,M,ru,1.83,0.0,OTHD,BLA,0,interpol-red-2012-325494
93497,C093498,RAJ HASSAN,1976-11-13,M,ru,NaN,NaN,nan,BROD,0,interpol-red-2012-325494
96010,C096011,TAI CHEN,1993-06-18,M,ru,NaN,NaN,BLA,nan,0,interpol-red-2012-325494
96449,C096450,YACUP GALIEV,1965-02-07,F,ru,NaN,0.0,nan,nan,0,interpol-red-2012-325494
96500,C096501,JOSE BAUTISTA,1974-10-14,M,ru,1.65,0.0,BLA,nan,0,interpol-red-2012-325494
98241,C098242,TAI CHEN,1990-05-18,M,ru,1.78,0.0,nan,BRO,0,interpol-red-2012-325494
98757,C098758,TAI CHEN,1974-05-27,M,pk,NaN,NaN,nan,BRO,0,interpol-red-2012-325494
99259,C099260,TAI CHEN,1984-11-17,F,sv,NaN,59.0,BLA,nan,0,interpol-red-2012-325494