In [1]:
import pandas as pd
import numpy as np
import random
import ast

from dateutil.relativedelta import relativedelta
from datetime import date

import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

In [2]:
origin_df = pd.read_excel('processed/origin_complete.xlsx')
crime_analysis = pd.read_csv('processed/crime_analysis_results.csv')

In [3]:
print("""
Crime analysis data (from Audrey)
- id, name, aliases
- birth_date, haircolour, height, eyecolour, gender, age_at_first_seen, days_at_large, age_today, age_last_seen
- countries (code of country), Label (country label), address (lowercase ones), sanctions_cleaned, phones, emails
- schema, program_ids, dataset, first_seen, last_seen, last_change

Origin (including network links)
- id, entity_id
- weight, language_spoken_ids, distinguishing_marks
- _embedded.links
- '_links.self.href', '_links.images.href', '_links.thumbnail.href'

""")

df1_cols = [
    'id', 'name', 'aliases',
    'birth_date', 'hairColor', 'height', 'eyeColor', 'GENDER', 'age_at_first_seen', 'days_at_large', 'age_today', 'age_at_last_seen',
    'countries', 'Label', 'address', 'sanctions_clean', 'phones', 'emails',
    'schema', 'program_ids', 'dataset', 'first_seen', 'last_seen', 'last_change'
]

df2_cols = [
    'id', 'entity_id',
    'weight', 'languages_spoken_ids', 'distinguishing_marks',
    '_embedded.links',
    '_links.self.href', '_links.images.href', '_links.thumbnail.href'
]

df1_select = crime_analysis[df1_cols]
df2_select = origin_df[df2_cols]

# display(origin_df)
# display(crime_analysis)

df_final = pd.merge(df1_select, df2_select, on = 'id')
display(df_final)

Crime analysis data (from Audrey)
- id, name, aliases
- birth_date, haircolour, height, eyecolour, gender, age_at_first_seen, days_at_large, age_today, age_last_seen
- countries (code of country), Label (country label), address (lowercase ones), sanctions_cleaned, phones, emails
- schema, program_ids, dataset, first_seen, last_seen, last_change

Origin (including network links)
- id, entity_id
- weight, language_spoken_ids, distinguishing_marks
- _embedded.links
- '_links.self.href', '_links.images.href', '_links.thumbnail.href'

,id,name,aliases,birth_date,hairColor,height,eyeColor,GENDER,age_at_first_seen,days_at_large,age_today,age_at_last_seen,countries,Label,address,sanctions_clean,phones,emails,schema,program_ids,dataset,first_seen,last_seen,last_change,entity_id,weight,languages_spoken_ids,distinguishing_marks,_embedded.links,_links.self.href,_links.images.href,_links.thumbnail.href
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,"['TGK', 'ARA', 'ENG', 'RUS']",NaN,"[{'forename': 'ANDREY', 'color': 'RED', 'name'...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
1,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,tj,Tajikistan,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,"['TGK', 'ARA', 'ENG', 'RUS']",NaN,"[{'forename': 'ANDREY', 'color': 'RED', 'name'...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
2,NK-22baaNEkbgBeZokNLmpaKd,DZHAMBULAT GALIMOV,NaN,1989-01-05,NaN,NaN,NaN,M,35.2,667,36,37.2,ru,Russia,dagestan republic,participation in illegal armed formation,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2016/62557,0.0,"['RUS', 'KUM']",NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
3,NK-282timUs47w9otBkgPN6hw,KHAVA EFENDIEVA,NaN,1982-05-24,BLA,1.75,BLA,F,41.8,667,43,42.8,ru,Russia,"grozny, chechen republic",participation in illegal armed formation,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2021/16004,0.0,['RUS'],NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
4,NK-2Ld7pewCoLeyspMtVCMMMo,JIAN XIA,NaN,1977-07-13,NaN,NaN,NaN,M,46.6,667,48,47.6,cn,China,liaoning,"""1) murder\n2) manslaughter\n3) aggravated theft""",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2010/24537,0.0,"['CHI', 'ENG']",NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6999,interpol-red-2026-6812,MICHAL ZBIGNIEW BARYS,NaN,1978-10-22,NaN,NaN,NaN,M,47.3,-33,47,46.4,pl,Poland,warszawa,"""tax fraud\ninvoice forgery""",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-02-02 18:27:02,2026-03-07 09:27:01,2026-02-02 18:27:02,2026/6812,NaN,NaN,NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
7000,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.80,BRO,M,47.0,-12,46,47.1,no,Norway,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,NaN,NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
7001,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.80,BRO,M,47.0,-12,46,47.1,pk,Pakistan,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,NaN,NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
7002,interpol-red-2026-6996,MILOS MEDENICA,NaN,1986-05-20,NaN,NaN,NaN,M,39.7,-31,39,38.8,me,Montenegro,kolasin,"""– establishment of a criminal organization, \...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/6996,NaN,['SRP'],NaN,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
7003,interpol-red-2026-7397,ALEXANDER JAVIER QUIJADA MOJICA,NaN,2000-04-24,BLA,NaN,NaN,M,25.8,-31,25,24.9,pa,Panama,panama,homicidio,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/7397,0.0,NaN,TEZ CLARA,[],https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN

In [4]:
def process_list_string(s):
    if pd.isna(s): # Handles actual NaN values in the column
        return None
    try:
        # Try evaluating after replacing 'nan' with 'None'
        return ast.literal_eval(s.replace('nan', 'None'))
    except (ValueError, SyntaxError):
        # Handle cases where the string is not a list format, e.g., a single value
        return s

def normalise_data(df, col):
    normalised = pd.json_normalize(df)
    normalised = normalised.add_prefix('(' + col +')')
    return normalised

def calculate_detailed_age(born):
    # Check if 'born' is NaT or None
    if pd.isnull(born):
        return None
    
    today = date.today()
    # Ensure 'born' is a date object, as pandas timestamps can sometimes 
    # behave differently with relativedelta
    age = relativedelta(today, born.date())
    return age

In [5]:
df_final['languages_spoken_ids'] = df_final['languages_spoken_ids'].apply(process_list_string)
df_final['_embedded.links'] = df_final['_embedded.links'].apply(process_list_string)

In [6]:
cols_to_explode = ['languages_spoken_ids', '_embedded.links']

for col in cols_to_explode:
    df_final = df_final.explode(col)

In [7]:
df_final = df_final.reset_index(drop=True)
df_final

,id,name,aliases,birth_date,hairColor,height,eyeColor,GENDER,age_at_first_seen,days_at_large,age_today,age_at_last_seen,countries,Label,address,sanctions_clean,phones,emails,schema,program_ids,dataset,first_seen,last_seen,last_change,entity_id,weight,languages_spoken_ids,distinguishing_marks,_embedded.links,_links.self.href,_links.images.href,_links.thumbnail.href
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
1,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ARA,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
2,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ENG,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
3,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,RUS,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
4,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,tj,Tajikistan,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10028,interpol-red-2026-6812,MICHAL ZBIGNIEW BARYS,NaN,1978-10-22,NaN,NaN,NaN,M,47.3,-33,47,46.4,pl,Poland,warszawa,"""tax fraud\ninvoice forgery""",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-02-02 18:27:02,2026-03-07 09:27:01,2026-02-02 18:27:02,2026/6812,NaN,None,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
10029,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,no,Norway,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
10030,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,pk,Pakistan,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
10031,interpol-red-2026-6996,MILOS MEDENICA,NaN,1986-05-20,NaN,NaN,NaN,M,39.7,-31,39,38.8,me,Montenegro,kolasin,"""– establishment of a criminal organization, \...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/6996,NaN,SRP,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
10032,interpol-red-2026-7397,ALEXANDER JAVIER QUIJADA MOJICA,NaN,2000-04-24,BLA,NaN,NaN,M,25.8,-31,25,24.9,pa,Panama,panama,homicidio,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/7397,0.0,None,TEZ CLARA,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN

In [8]:
df_normalise = pd.concat([df_final, normalise_data(df_final['_embedded.links'], 'embedded_links')], axis= 1)
df_normalise

,id,name,aliases,birth_date,hairColor,height,eyeColor,GENDER,age_at_first_seen,days_at_large,age_today,age_at_last_seen,countries,Label,address,sanctions_clean,phones,emails,schema,program_ids,dataset,first_seen,last_seen,last_change,entity_id,weight,languages_spoken_ids,distinguishing_marks,_embedded.links,_links.self.href,_links.images.href,_links.thumbnail.href,(embedded_links)forename,(embedded_links)color,(embedded_links)name,(embedded_links)entity_id,(embedded_links)_links.self.href,(embedded_links)_links.thumbnail.href
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,ANDREY,RED,NIKITENKO,2019/102608,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
1,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ARA,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,ANDREY,RED,NIKITENKO,2019/102608,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
2,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ENG,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,ANDREY,RED,NIKITENKO,2019/102608,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
3,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,RUS,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,ANDREY,RED,NIKITENKO,2019/102608,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
4,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,tj,Tajikistan,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,"{'forename': 'ANDREY', 'color': 'RED', 'name':...",https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,ANDREY,RED,NIKITENKO,2019/102608,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10028,interpol-red-2026-6812,MICHAL ZBIGNIEW BARYS,NaN,1978-10-22,NaN,NaN,NaN,M,47.3,-33,47,46.4,pl,Poland,warszawa,"""tax fraud\ninvoice forgery""",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-02-02 18:27:02,2026-03-07 09:27:01,2026-02-02 18:27:02,2026/6812,NaN,None,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN,NaN,NaN,NaN,NaN
10029,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,no,Norway,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN,NaN,NaN,NaN,NaN
10030,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,pk,Pakistan,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN,NaN,NaN,NaN,NaN
10031,interpol-red-2026-6996,MILOS MEDENICA,NaN,1986-05-20,NaN,NaN,NaN,M,39.7,-31,39,38.8,me,Montenegro,kolasin,"""– establishment of a criminal organization, \...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/6996,NaN,SRP,NaN,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN,NaN,NaN,NaN,NaN
10032,interpol-red-2026-7397,ALEXANDER JAVIER QUIJADA MOJICA,NaN,2000-04-24,BLA,NaN,NaN,M,25.8,-31,25,24.9,pa,Panama,panama,homicidio,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/7397,0.0,None,TEZ CLARA,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_normalise = df_normalise.drop(columns = [ '_embedded.links'])

In [10]:
df_normalise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10033 entries, 0 to 10032
Data columns (total 37 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     10033 non-null  object
 1   name                                   10033 non-null  object
 2   aliases                                6 non-null      object
 3   birth_date                             9756 non-null   object
 4   hairColor                              5063 non-null   object
 5   height                                 4885 non-null   float64
 6   eyeColor                               4535 non-null   object
 7   GENDER                                 10028 non-null  object
 8   age_at_first_seen                      9756 non-null   float64
 9   days_at_large                          10033 non-null  int64
 10  age_today                              10033 non-null  int64
 11  age_at_last_seen                       9756 non-null   float64
 12  countries                              9984 non-null   object
 13  Label                                  9984 non-null   object
 14  address                                10033 non-null  object
 15  sanctions_clean                        10032 non-null  object
 16  phones                                 0 non-null      float64
 17  emails                                 0 non-null      float64
 18  schema                                 10033 non-null  object
 19  program_ids                            10032 non-null  object
 20  dataset                                10033 non-null  object
 21  first_seen                             10033 non-null  object
 22  last_seen                              10033 non-null  object
 23  last_change                            10033 non-null  object
 24  entity_id                              10033 non-null  object
 25  weight                                 8139 non-null   float64
 26  languages_spoken_ids                   9233 non-null   object
 27  distinguishing_marks                   1140 non-null   object
 28  _links.self.href                       10033 non-null  object
 29  _links.images.href                     10033 non-null  object
 30  _links.thumbnail.href                  9665 non-null   object
 31  (embedded_links)forename               257 non-null    object
 32  (embedded_links)color                  257 non-null    object
 33  (embedded_links)name                   257 non-null    object
 34  (embedded_links)entity_id              257 non-null    object
 35  (embedded_links)_links.self.href       257 non-null    object
 36  (embedded_links)_links.thumbnail.href  251 non-null    object
dtypes: float64(6), int64(2), object(29)
memory usage: 2.8+ MB

In [11]:
df_normalise['network_name'] = df_normalise['(embedded_links)forename'] + ' ' + df_normalise['(embedded_links)name']
df_normalise = df_normalise.rename(columns = {'(embedded_links)entity_id': 'network_entity_id'})
df_normalise = df_normalise.drop(columns = [
    '(embedded_links)color',
    '(embedded_links)forename',
    '(embedded_links)name',
    '(embedded_links)_links.self.href',
    '(embedded_links)_links.thumbnail.href'
])
df_normalise

,id,name,aliases,birth_date,hairColor,height,eyeColor,GENDER,age_at_first_seen,days_at_large,age_today,age_at_last_seen,countries,Label,address,sanctions_clean,phones,emails,schema,program_ids,dataset,first_seen,last_seen,last_change,entity_id,weight,languages_spoken_ids,distinguishing_marks,_links.self.href,_links.images.href,_links.thumbnail.href,network_entity_id,network_name
0,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,2019/102608,ANDREY NIKITENKO
1,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ARA,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,2019/102608,ANDREY NIKITENKO
2,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,ENG,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,2019/102608,ANDREY NIKITENKO
3,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,ru,Russia,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,RUS,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,2019/102608,ANDREY NIKITENKO
4,NK-224TRezPqwzhQZ37exWxtX,SANAVBARI NIKITENKO,NaN,1992-06-28,OTHD,NaN,OTHD,F,31.7,667,33,32.7,tj,Tajikistan,kofarnikhon town,"""participation in the activity of a terrorist ...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2024-03-04 17:09:51,2026-03-07 09:27:01,2025-10-06 18:27:01,2019/108810,0.0,TGK,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,2019/102608,ANDREY NIKITENKO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10028,interpol-red-2026-6812,MICHAL ZBIGNIEW BARYS,NaN,1978-10-22,NaN,NaN,NaN,M,47.3,-33,47,46.4,pl,Poland,warszawa,"""tax fraud\ninvoice forgery""",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-02-02 18:27:02,2026-03-07 09:27:01,2026-02-02 18:27:02,2026/6812,NaN,None,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN
10029,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,no,Norway,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN
10030,interpol-red-2026-688,MOHAMMAD SHAHZAD GULL,NaN,1979-01-19,BLA,1.8,BRO,M,47.0,-12,46,47.1,pk,Pakistan,gujranwala,norwegian penal code (1902) section 162 subs. ...,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-12 09:27:01,2026-03-07 09:27:01,2026-01-21 00:27:02,2026/688,NaN,None,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN
10031,interpol-red-2026-6996,MILOS MEDENICA,NaN,1986-05-20,NaN,NaN,NaN,M,39.7,-31,39,38.8,me,Montenegro,kolasin,"""– establishment of a criminal organization, \...",NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/6996,NaN,SRP,NaN,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN
10032,interpol-red-2026-7397,ALEXANDER JAVIER QUIJADA MOJICA,NaN,2000-04-24,BLA,NaN,NaN,M,25.8,-31,25,24.9,pa,Panama,panama,homicidio,NaN,NaN,Person,INTERPOL-RN,INTERPOL Red Notices,2026-01-31 00:27:03,2026-03-07 09:27:01,2026-01-31 00:27:03,2026/7397,0.0,None,TEZ CLARA,https://ws-public.interpol.int/notices/v1/red/...,https://ws-public.interpol.int/notices/v1/red/...,NaN,NaN,NaN

In [12]:
# save the mega data for synthetic data generation
df_normalise.to_csv('processed/mega_sanctions_final.csv', index=False)

## Generating Synthetic Client Data (To Train & Test Models)
Total Records: 10,000
- Matches (Sanctioned): 500 (5% of the data)
- Non-matches (Clean): 9,500 (95% of the data) - reflecting real-world scenarios where most clients are not sanctioned.
- Target Column: match_label (1 = Sanctioned, 0 = Clean).

The synthetic data includes only typical client-facing features, excluding internal sanction descriptions and crime details:
- client_id: A unique identifier (e.g., C000001).
- full_name: Realistic names derived and shuffled from the original dataset.
- date_of_birth: Formatted as YYYY-MM-DD.
- gender: M/F/Other.
- nationality_code: Two-letter country codes (e.g., ru, tj, co).
- height_cm & weight_kg: Numerical biometric data.
- hair_color & eye_color: Categorical biometric descriptors.
- spoken_languages: Three-letter language codes.

Key Considerations:
- Synthetic data maintains biometric sparsity (e.g. 50% of original data lacked hair colour and eye colour, which is reflected
- For the 500 matches, minor variations were introduced (e.g. name misspelling, height difference, date of birth alteration) to reflect real world data

In [13]:
# Load the dataset
df = pd.read_csv('processed/mega_sanctions_final.csv')

# Inspect the columns and the first few rows
print(df.columns.tolist())
print(df.head())
print(df.info())

# Identify columns suitable for client data
# name, birth_date, hairColor, height, eyeColor, GENDER, countries (maybe map to nationality), weight, languages_spoken_ids
client_cols = ['name', 'birth_date', 'hairColor', 'height', 'eyeColor', 'GENDER', 'countries', 'weight', 'languages_spoken_ids']

# Check missingness
missing_stats = df[client_cols].isnull().mean()
print("\nMissingness in client columns:")
print(missing_stats)

['id', 'name', 'aliases', 'birth_date', 'hairColor', 'height', 'eyeColor', 'GENDER', 'age_at_first_seen', 'days_at_large', 'age_today', 'age_at_last_seen', 'countries', 'Label', 'address', 'sanctions_clean', 'phones', 'emails', 'schema', 'program_ids', 'dataset', 'first_seen', 'last_seen', 'last_change', 'entity_id', 'weight', 'languages_spoken_ids', 'distinguishing_marks', '_links.self.href', '_links.images.href', '_links.thumbnail.href', 'network_entity_id', 'network_name']
                          id                 name aliases  birth_date  \
0  NK-224TRezPqwzhQZ37exWxtX  SANAVBARI NIKITENKO     NaN  1992-06-28
1  NK-224TRezPqwzhQZ37exWxtX  SANAVBARI NIKITENKO     NaN  1992-06-28
2  NK-224TRezPqwzhQZ37exWxtX  SANAVBARI NIKITENKO     NaN  1992-06-28
3  NK-224TRezPqwzhQZ37exWxtX  SANAVBARI NIKITENKO     NaN  1992-06-28
4  NK-224TRezPqwzhQZ37exWxtX  SANAVBARI NIKITENKO     NaN  1992-06-28

  hairColor  height eyeColor GENDER  age_at_first_seen  days_at_large  \
0      OTHD     NaN     OTHD      F               31.7            667
1      OTHD     NaN     OTHD      F               31.7            667
2      OTHD     NaN     OTHD      F               31.7            667
3      OTHD     NaN     OTHD      F               31.7            667
4      OTHD     NaN     OTHD      F               31.7            667

   age_today  age_at_last_seen countries       Label           address  \
0         33              32.7        ru      Russia  kofarnikhon town
1         33              32.7        ru      Russia  kofarnikhon town
2         33              32.7        ru      Russia  kofarnikhon town
3         33              32.7        ru      Russia  kofarnikhon town
4         33              32.7        tj  Tajikistan  kofarnikhon town

                                     sanctions_clean  phones  emails  schema  \
0  "participation in the activity of a terrorist ...     NaN     NaN  Person
1  "participation in the activity of a terrorist ...     NaN     NaN  Person
2  "participation in the activity of a terrorist ...     NaN     NaN  Person
3  "participation in the activity of a terrorist ...     NaN     NaN  Person
4  "participation in the activity of a terrorist ...     NaN     NaN  Person

   program_ids               dataset           first_seen  \
0  INTERPOL-RN  INTERPOL Red Notices  2024-03-04 17:09:51
1  INTERPOL-RN  INTERPOL Red Notices  2024-03-04 17:09:51
2  INTERPOL-RN  INTERPOL Red Notices  2024-03-04 17:09:51
3  INTERPOL-RN  INTERPOL Red Notices  2024-03-04 17:09:51
4  INTERPOL-RN  INTERPOL Red Notices  2024-03-04 17:09:51

             last_seen          last_change    entity_id  weight  \
0  2026-03-07 09:27:01  2025-10-06 18:27:01  2019/108810     0.0
1  2026-03-07 09:27:01  2025-10-06 18:27:01  2019/108810     0.0
2  2026-03-07 09:27:01  2025-10-06 18:27:01  2019/108810     0.0
3  2026-03-07 09:27:01  2025-10-06 18:27:01  2019/108810     0.0
4  2026-03-07 09:27:01  2025-10-06 18:27:01  2019/108810     0.0

  languages_spoken_ids distinguishing_marks  \
0                  TGK                  NaN
1                  ARA                  NaN
2                  ENG                  NaN
3                  RUS                  NaN
4                  TGK                  NaN

                                    _links.self.href  \
0  https://ws-public.interpol.int/notices/v1/red/...
1  https://ws-public.interpol.int/notices/v1/red/...
2  https://ws-public.interpol.int/notices/v1/red/...
3  https://ws-public.interpol.int/notices/v1/red/...
4  https://ws-public.interpol.int/notices/v1/red/...

                                  _links.images.href  \
0  https://ws-public.interpol.int/notices/v1/red/...
1  https://ws-public.interpol.int/notices/v1/red/...
2  https://ws-public.interpol.int/notices/v1/red/...
3  https://ws-public.interpol.int/notices/v1/red/...
4  https://ws-public.interpol.int/notices/v1/red/...

                               _links.thumbnail.href network_entity_id  \
0  https://ws-public.interpol.int/notices/v1/red/...       2019/102608
1  https://ws-public.interpol.int/notices/v1/red/...       2019/102608
2  https://ws-public.interpol.int/notices/v1/red/...       2019/102608
3  https://ws-public.interpol.int/notices/v1/red/...       2019/102608
4  https://ws-public.interpol.int/notices/v1/red/...       2019/102608

       network_name
0  ANDREY NIKITENKO
1  ANDREY NIKITENKO
2  ANDREY NIKITENKO
3  ANDREY NIKITENKO
4  ANDREY NIKITENKO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10033 entries, 0 to 10032
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     10033 non-null  object
 1   name                   10033 non-null  object
 2   aliases                6 non-null      object
 3   birth_date             9756 non-null   object
 4   hairColor              5063 non-null   object
 5   height                 4885 non-null   float64
 6   eyeColor               4535 non-null   object
 7   GENDER                 10028 non-null  object
 8   age_at_first_seen      9756 non-null   float64
 9   days_at_large          10033 non-null  int64
 10  age_today              10033 non-null  int64
 11  age_at_last_seen       9756 non-null   float64
 12  countries              9984 non-null   object
 13  Label                  9984 non-null   object
 14  address                10033 non-null  object
 15  sanctions_clean        10032 non-null  object
 16  phones                 0 non-null      float64
 17  emails                 0 non-null      float64
 18  schema                 10033 non-null  object
 19  program_ids            10032 non-null  object
 20  dataset                10033 non-null  object
 21  first_seen             10033 non-null  object
 22  last_seen              10033 non-null  object
 23  last_change            10033 non-null  object
 24  entity_id              10033 non-null  object
 25  weight                 8139 non-null   float64
 26  languages_spoken_ids   9233 non-null   object
 27  distinguishing_marks   1140 non-null   object
 28  _links.self.href       10033 non-null  object
 29  _links.images.href     10033 non-null  object
 30  _links.thumbnail.href  9665 non-null   object
 31  network_entity_id      257 non-null    object
 32  network_name           257 non-null    object
dtypes: float64(6), int64(2), object(25)
memory usage: 2.5+ MB
None

Missingness in client columns:
name                    0.000000
birth_date              0.027609
hairColor               0.495365
height                  0.513107
eyeColor                0.547992
GENDER                  0.000498
countries               0.004884
weight                  0.188777
languages_spoken_ids    0.079737
dtype: float64

In [14]:
# Select client columns
client_cols = ['name', 'birth_date', 'hairColor', 'height', 'eyeColor', 'GENDER', 'countries', 'weight', 'languages_spoken_ids']

# Extract distributions for non-matches
distributions = {}
for col in client_cols:
    if col != 'name':
        # Get counts including NaNs
        distributions[col] = df[col].value_counts(dropna=False, normalize=True)

# Function to generate synthetic names for non-matches
# We can split existing names and shuffle them.
names = df['name'].dropna().unique()
first_names = [n.split()[0] for n in names if len(n.split()) > 0]
last_names = [n.split()[-1] for n in names if len(n.split()) > 1]

def generate_random_name():
    fn = np.random.choice(first_names)
    ln = np.random.choice(last_names)
    return f"{fn} {ln}"

# Check distributions
print(distributions['GENDER'])
print(distributions['hairColor'].head())

GENDER
M      0.866042
F      0.133460
NaN    0.000498
Name: proportion, dtype: float64
hairColor
NaN     0.495365
BLA     0.282269
OTHD    0.144324
BRO     0.034785
BROF    0.013256
Name: proportion, dtype: float64

In [18]:
# Number of rows
n_total = 10000
n_matches = 500 # 5% of data will be matched to sanctions
n_non_matches = n_total - n_matches

# 1. GENERATE MATCHES
# Select 500 random records from the sanctions list
matches_orig = df.sample(n=n_matches, random_state=42)

# Select client-relevant columns
client_map = {
    'name': 'full_name',
    'birth_date': 'date_of_birth',
    'GENDER': 'gender',
    'countries': 'nationality_code',
    'height': 'height_cm',
    'weight': 'weight_kg',
    'hairColor': 'hair_color',
    'eyeColor': 'eye_color',
    'languages_spoken_ids': 'spoken_languages'
}

matches = matches_orig[list(client_map.keys()) + ['id']].rename(columns=client_map)
matches = matches.rename(columns={'id': 'matched_sanction_id'})

# For half of the matches, let's introduce some variability to simulate real-world data
def introduce_fuzzy(row):
    """
    Role the dice to choose whether we create variability for name, height, or birth date
    The names will be altered through random swapping of characters for names length > 5
    The date of birth will be altered at either year, month, day or mixed:
        - year: 1 to 3
        - month: 1 to 6
        - day: 1 to 20
    The height will be altered by +- 1 to 5cm if height is not null
    """
    # Misspell name slightly
    name = str(row['full_name'])
    if len(name) > 5:
        strategy = random.choice(['swap', 'shuffle_slice', 'drop', 'duplicate'])
        char_list = list(name)
        
        if strategy == 'swap':
            idx = random.randint(0, len(char_list) - 2)
            char_list[idx], char_list[idx+1] = char_list[idx+1], char_list[idx]
            
        elif strategy == 'shuffle_slice':
            slice_len = min(random.randint(3, 4), len(char_list))
            start_idx = random.randint(0, len(char_list) - slice_len)
            slice_chars = char_list[start_idx:start_idx + slice_len]
            random.shuffle(slice_chars)
            char_list[start_idx:start_idx + slice_len] = slice_chars
            
        elif strategy == 'drop':
            char_list.pop(random.randint(0, len(char_list) - 1))
            
        elif strategy == 'duplicate':
            idx = random.randint(0, len(char_list) - 1)
            char_list.insert(idx, char_list[idx])
        
        row['full_name'] = "".join(char_list)
        
     # Modify height by +/- 1 to 5
    if pd.notnull(row['height_cm']) and row['height_cm'] > 0:
        row['height_cm'] += random.randint(-5, 5)
    
    # Modify age anywhere between 1 to 3 years, 1 to 6 months, 1 to 20 days
    if pd.notnull(row['date_of_birth']):
        try:
            dt = pd.to_datetime(row['date_of_birth'])
            
            # Pick a random shift type
            shift_type = random.choice(['year', 'month', 'day', 'mix'])
            
            if shift_type == 'year':
                # Shift 1 to 3 years
                dt += relativedelta(years=random.randint(1, 3) * random.choice([-1, 1])) # change from 10 years to 3 years (+/-)
            elif shift_type == 'month':
                # Shift 1 to 6 months
                dt += relativedelta(months=random.randint(1, 6) * random.choice([-1, 1]))
            elif shift_type == 'day':
                # Shift 1 to 20 days
                dt += relativedelta(days=random.randint(1, 20) * random.choice([-1, 1]))
            else:
                # A mix of small changes to simulate general data entry error
                dt += relativedelta(
                    years=random.randint(0, 2) * random.choice([-1, 1]),
                    months=random.randint(0, 3) * random.choice([-1, 1]),
                    days=random.randint(1, 10) * random.choice([-1, 1])
                )
            
            row['date_of_birth'] = dt.strftime('%Y-%m-%d')
        except Exception:
            pass # Fallback in case of conversion errors
    return row

matches = matches.apply(introduce_fuzzy, axis=1)
matches['match_label'] = 1

# 2. GENERATE NON-MATCHES
# Define non-match data
non_matches_data = {}

# Sample random IDs from original sanctions list for non-matches
matches_id = set(matches_orig)
df_non_matches = df[~df['id'].isin(matches_id)]
non_matches_data['matched_sanction_id'] = df_non_matches['id'].sample(n=n_non_matches, replace=True, random_state=7).values

# display(non_matches_data)

# Distribution sampling function
def sample_from_dist(col_name, size):
    """
    Helper function to randomly sample data from original sanctions dataset for the non-matched clients.
    The rest of the unsampled data will have random generated names
    """
    dist = distributions[col_name]
    values = dist.index.tolist()
    probs = dist.values.tolist()
    # Handle NaNs properly in choice
    # values can contain np.nan which is fine for np.random.choice if we handle the list correctly
    sampled = np.random.choice(values, size=size, p=probs)
    return sampled

for orig_col, new_col in client_map.items():
    if orig_col == 'name':
        # Generate random names
        non_matches_data[new_col] = [generate_random_name() for _ in range(n_non_matches)]
    else:
        non_matches_data[new_col] = sample_from_dist(orig_col, n_non_matches)

non_matches = pd.DataFrame(non_matches_data)
non_matches['match_label'] = 0

# Ensure non-matches aren't actually in the sanctions list by checking names
sanctioned_names = set(df['name'].str.upper().tolist())
# If a generated name is in sanctioned_names, regenerate it
non_matches['full_name'] = non_matches['full_name'].apply(
    lambda x: generate_random_name() if str(x).upper() in sanctioned_names else x
)

# 3. COMBINE AND SHUFFLE
synthetic_df = pd.concat([matches, non_matches], ignore_index=True)
synthetic_df = synthetic_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Add a synthetic client_id
synthetic_df['client_id'] = ['C' + str(i).zfill(6) for i in range(1, n_total + 1)]

# Reorder columns
final_cols = ['client_id', 'full_name', 'date_of_birth', 'gender', 'nationality_code',
              'height_cm', 'weight_kg', 'hair_color', 'eye_color', 'spoken_languages', 'match_label', 'matched_sanction_id']
synthetic_df = synthetic_df[final_cols]

display(synthetic_df)

# Save to CSV
synthetic_df.to_csv('synthetic_client_data.csv', index=False)

# Quick check on distributions
print("\nSynthetic data missingness:")
print(synthetic_df.isnull().mean())
print("\nMatch count:")
print(synthetic_df['match_label'].value_counts())
print("\nFirst 10 rows:")
print(synthetic_df.head(10))

,client_id,full_name,date_of_birth,gender,nationality_code,height_cm,weight_kg,hair_color,eye_color,spoken_languages,match_label,matched_sanction_id
0,C000001,DMITRIY OZDOEVA,1981-10-03,M,br,1.68,0.0,nan,nan,POR,0,interpol-red-1997-3388
1,C000002,JASARAT LÓPEZ,1985-06-02,M,ru,NaN,79.0,nan,BLA,LEZ,0,interpol-red-2002-803
2,C000003,XIAOBO JAKELAITIENE,1968-07-18,M,in,NaN,85.0,OTHD,nan,HIN,0,interpol-red-2023-30594
3,C000004,KHAKIM GAITUKAEVA,1980-05-06,M,ru,NaN,0.0,nan,nan,ENG,0,Q553191
4,C000005,MOHAMED ABDURAKOV,1973-09-11,M,ua,NaN,60.0,nan,BROH,RUS,0,interpol-red-2012-325494
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C009996,HENRY MARTÍNEZ,1977-10-08,M,ru,1.70,0.0,nan,nan,ARA,0,NK-224TRezPqwzhQZ37exWxtX
9996,C009997,ABDULNETIF ISMAILOVA,1967-05-12,M,ru,1.80,NaN,BLA,nan,AZE,0,interpol-red-2017-131645
9997,C009998,DZHAMBULAT SOLORZANO,1948-11-28,F,az,NaN,0.0,OTHD,nan,ARA,0,interpol-red-2019-36516
9998,C009999,TAMERLAN YAKHNOVSKIY,1984-03-19,M,ru,1.71,0.0,BLA,nan,CHE,0,interpol-red-2005-37909
9999,C010000,JORGE BERNAL,1993-11-26,M,ni,NaN,84.0,BLA,nan,TUR,0,interpol-red-2019-13345

Synthetic data missingness:
client_id              0.0000
full_name              0.0000
date_of_birth          0.0012
gender                 0.0000
nationality_code       0.0003
height_cm              0.5132
weight_kg              0.1880
hair_color             0.0262
eye_color              0.0279
spoken_languages       0.0050
match_label            0.0000
matched_sanction_id    0.0000
dtype: float64

Match count:
match_label
0    9500
1     500
Name: count, dtype: int64

First 10 rows:
  client_id                          full_name date_of_birth gender  \
0   C000001                    DMITRIY OZDOEVA    1981-10-03      M
1   C000002                      JASARAT LÓPEZ    1985-06-02      M
2   C000003                XIAOBO JAKELAITIENE    1968-07-18      M
3   C000004                  KHAKIM GAITUKAEVA    1980-05-06      M
4   C000005                  MOHAMED ABDURAKOV    1973-09-11      M
5   C000006               ERLANBEK OSTAPCHENKO    1969-01-09      M
6   C000007                 CRISTINA RODRIGUEZ    1995-07-09      M
7   C000008                      RENAT KHATUEV    1970-10-19      M
8   C000009                NIURDZHAN RAMAZANOV    1978-01-01      M
9   C000010  ADRIANA HERLIDAN ARANGO JARAMILLO    1965-08-17      F

  nationality_code  height_cm  weight_kg hair_color eye_color  \
0               br       1.68        0.0        nan       nan
1               ru        NaN       79.0        nan       BLA
2               in        NaN       85.0       OTHD       nan
3               ru        NaN        0.0        nan       nan
4               ua        NaN       60.0        nan      BROH
5               us       1.72        NaN       REDA      BROH
6              nan       1.60       61.0        nan      BROH
7               zw       1.55        NaN        BLA       BLA
8               es        NaN        0.0        nan       BRO
9               co        NaN        0.0        BRO       BRO

  spoken_languages  match_label       matched_sanction_id
0              POR            0    interpol-red-1997-3388
1              LEZ            0     interpol-red-2002-803
2              HIN            0   interpol-red-2023-30594
3              ENG            0                   Q553191
4              RUS            0  interpol-red-2012-325494
5              RUS            0   interpol-red-2016-61471
6              SPA            0   interpol-red-2018-22973
7              LEZ            0   interpol-red-2018-86161
8              URD            0  interpol-red-2018-107533
9              ENG            1   interpol-red-2008-17711

In [19]:
# Debugging missingness
print("Data types in synthetic_df:")
print(synthetic_df.dtypes)

# Check if 'nan' is a string
print("\nIs 'nan' a string in hair_color?")
print(synthetic_df['hair_color'].apply(lambda x: str(x).lower() == 'nan').mean())

# Fix the distribution sampling to ensure NaN is handled correctly as a real null
def sample_from_dist_fixed(col_name, size):
    dist = distributions[col_name]
    values = dist.index.tolist()
    probs = dist.values.tolist()
    # Replace any string 'nan' or actual nan with a placeholder if needed,
    # but the best way is to keep them as objects and then ensure they are np.nan
    sampled = np.random.choice(len(values), size=size, p=probs)
    return [values[i] for i in sampled]

# Re-generate non-matches with the fix
for orig_col, new_col in client_map.items():
    if orig_col == 'name':
        pass # already done
    else:
        non_matches[new_col] = sample_from_dist_fixed(orig_col, n_non_matches)

# Re-combine
synthetic_df = pd.concat([matches, non_matches], ignore_index=True)
synthetic_df = synthetic_df.sample(frac=1, random_state=42).reset_index(drop=True)
synthetic_df['client_id'] = ['C' + str(i).zfill(6) for i in range(1, n_total + 1)]
synthetic_df = synthetic_df[final_cols]

# Final verification
print("\nCorrected Synthetic data missingness (isnull()):")
print(synthetic_df.isnull().mean())

# Save again
synthetic_df.to_csv('synthetic_client_data.csv', index=False)

Data types in synthetic_df:
client_id               object
full_name               object
date_of_birth           object
gender                  object
nationality_code        object
height_cm              float64
weight_kg              float64
hair_color              object
eye_color               object
spoken_languages        object
match_label              int64
matched_sanction_id     object
dtype: object

Is 'nan' a string in hair_color?
0.4955

Corrected Synthetic data missingness (isnull()):
client_id              0.0000
full_name              0.0000
date_of_birth          0.0282
gender                 0.0002
nationality_code       0.0052
height_cm              0.5143
weight_kg              0.1936
hair_color             0.4954
eye_color              0.5449
spoken_languages       0.0781
match_label            0.0000
matched_sanction_id    0.0000
dtype: float64